# Generated by Django 4.2.5 on 2023-11-13 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_cartitem_remove_cartitems_cart_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
